<a href="https://colab.research.google.com/github/PaulToronto/Stanford-Andrew-Ng-Machine-Learning-Specialization/blob/main/1_2_1_3_Lab_Python%2C_Numpy_and_Vectorizaionipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab - Python, Numpy and Vectorization

## Imports

In [1]:
import numpy as np
import time

## Reference

- Numpy documentation: https://numpy.org/doc/stable/
- Numpy broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html

## Vector creation in `numpy`

In [2]:
a = np.zeros(4)
a

array([0., 0., 0., 0.])

In [3]:
a.shape, a.dtype

((4,), dtype('float64'))

In [4]:
a = np.zeros((4, ))
a

array([0., 0., 0., 0.])

In [5]:
# [0.0, 1.0)
a = np.random.random_sample(4)
a

array([0.65849825, 0.02230642, 0.18135672, 0.15988089])

In [6]:
a = np.arange(4.)
a

array([0., 1., 2., 3.])

In [7]:
a = np.random.rand(4)
a

array([0.98406446, 0.35811863, 0.38085535, 0.08952248])

In [8]:
a = np.array([5, 4, 3, 2])
a

array([5, 4, 3, 2])

In [9]:
a.dtype

dtype('int64')

In [10]:
a = np.array([5., 2, 3, 2])
a.dtype

dtype('float64')

## Operations on Vectors

In [11]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
a[2], a[2].shape

(2, ())

In [13]:
a[-1]

9

## Slicing

In [14]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
#start:stop:step
a[2:7:1]

array([2, 3, 4, 5, 6])

In [16]:
a[2:7:2]

array([2, 4, 6])

## Vector operations

In [17]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [18]:
-a

array([-1, -2, -3, -4])

In [19]:
np.sum(a), a.sum()

(10, 10)

In [20]:
np.mean(a), a.mean()

(2.5, 2.5)

In [21]:
a**2

array([ 1,  4,  9, 16])

## Vector-vector elment-wise operations

In [22]:
a = np.array([1, 2, 3, 4])
b = np.array([-1, -2, 3, 4])

In [23]:
a + b

array([0, 0, 6, 8])

```python
c = np.array([1, 2])
a + c
```

ValueError: operands could not be broadcast together with shapes (4,) (2,)

## Scalar-vector operations

In [24]:
a

array([1, 2, 3, 4])

In [25]:
5 * a

array([ 5, 10, 15, 20])

## Vector-vector dot product

In [26]:
a = np.array([1, 2, 3])
b = np.array([10, 11, 12])

a.dot(b), 10 + 22 + 36

(68, 68)

## Vectorization and speed

In [27]:
def my_dot(a, b):
    """
   Compute the dot product of two vectors

    Args:
      a (ndarray (n,)):  input vector
      b (ndarray (n,)):  input vector with same dimension as a

    Returns:
      x (scalar):
    """
    x=0
    for i in range(a.shape[0]):
        x = x + a[i] * b[i]
    return x

In [28]:
np.random.seed(1)
a = np.random.rand(10_000_000)
b = np.random.rand(10_000_000)

In [29]:
tic = time.time()
np.dot(a, b)
toc = time.time()

print(1000 * (toc - tic), " ms")

tic = time.time()
a.dot(b)
toc = time.time()

print(1000 * (toc - tic), " ms")

tic = time.time()
my_dot(a, b)
toc = time.time()

print(1000 * (toc - tic), " ms")

# remove these big arrays from memore
del(a); del(b)

5.228757858276367  ms
5.112886428833008  ms
2186.7847442626953  ms


## Vector-vector operations in this course

- `X_train` will be stored in an array of dimension `(m,n)`, which is a 2-dimensional array
- `w` will be stored in a 1-dimensional array of shape `(n,)`
- we will perform operations by looping through the examples, extracting each example to work individually by indexing `X`, for example `X[i]`
- `X[i]` returns a value of shape `(n,)`, a 1-dimensional vector, consquently, operations involving `X[i]` are vector-vector

In [30]:
X = np.array([[1], [2], [3], [4]])
X

array([[1],
       [2],
       [3],
       [4]])

In [31]:
X.shape

(4, 1)

In [32]:
X[1].shape

(1,)

In [33]:
X[1]

array([2])

In [34]:
w = np.array([2])
w

array([2])

In [35]:
w.shape

(1,)

In [36]:
c = np.dot(X[1], w)
c

4

In [37]:
c.shape

()

## Matrices

- Matrices are 2-dimensional arrays

## Matrix Creatioin

In [38]:
A = np.zeros((1, 5))
A

array([[0., 0., 0., 0., 0.]])

In [39]:
A.shape

(1, 5)

In [40]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [41]:
a.shape

(5,)

In [42]:
A = np.array([[5],
              [4],
              [3]])

A

array([[5],
       [4],
       [3]])

In [43]:
A.shape

(3, 1)

In [44]:
A.T

array([[5, 4, 3]])

In [45]:
A.T.shape

(1, 3)

In [46]:
A = np.array((2, 1))
A

array([2, 1])

In [47]:
A.shape

(2,)

## Operations on Matrices

In [48]:
A = np.arange(6)
A

array([0, 1, 2, 3, 4, 5])

In [49]:
A = A.reshape(-1, 2)
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [50]:
A[2, 0]

4

In [51]:
A[2, 0].shape

()

In [52]:
A[2]

array([4, 5])

## Slicing

In [53]:
A = np.arange(20).reshape(-1, 10)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [54]:
A[0, 2:7:1]

array([2, 3, 4, 5, 6])

In [55]:
A[:, 2:7:1]

array([[ 2,  3,  4,  5,  6],
       [12, 13, 14, 15, 16]])

In [56]:
A[:,:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [57]:
A[1]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])