<a href="https://colab.research.google.com/github/PaulToronto/Stanford-Andrew-Ng-Machine-Learning-Specialization/blob/main/2_1_3_TensorFlow_implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2.1.3 TensorFlow implementation

## Imports

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

## 2.1.3.1 Inference in Code

One of the remarkable things about neural networks is that the same algorithm can be applied to so many different applications

### Coffee Roasting Example

- This is classification problem with two classes: good coffee and bad coffee
- This is a simplified example, but there have been real projects using machine learning to optimize coffee roasting

<img src='https://drive.google.com/uc?export=view&id=1vj4T81K1F-6sVk1qk5hBN9C_uydLpIrr'>

- Task: given temperature 200 and duration 17, will we get good coffee or not?

Given:

$$
\vec{x} = \begin{bmatrix}200 \\ 17\end{bmatrix}
$$

Determine: $\widehat{y} = 1$ (good coffee) or $\widehat{y} = 0$ (bad coffee)

<img src='https://drive.google.com/uc?export=view&id=1q41OMoxQF25yw5IsrpKuejmzu4BXB7se'>

- these are the key steps to forward propagation

  

In [2]:
x = np.array([[200.0, 17.0]])
layer_1 = tf.keras.layers.Dense(units=3, activation='sigmoid')
layer_1

In [3]:
a1 = layer_1(x)
a1

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[1., 1., 1.]], dtype=float32)>

In [4]:
a1.numpy()

array([[1., 1., 1.]], dtype=float32)

In [5]:
a1.shape

TensorShape([1, 3])

In [6]:
layer_2 = tf.keras.layers.Dense(units=1, activation='sigmoid')

In [7]:
a2 = layer_2(a1)
a2

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.86750245]], dtype=float32)>

In [8]:
a2.numpy()

array([[0.86750245]], dtype=float32)

In [9]:
# alternately
model = Sequential([
    layer_1,
    layer_2
])

model

In [10]:
# this is the same value we got above
#  using `a2.numpy()`
model.predict(x)

1/1 [==============================] - 0s 212ms/step


array([[0.86750245]], dtype=float32)

### Model for digit classification

<img src='https://drive.google.com/uc?export=view&id=11lAGLR3geOaPtgtgds2F1h65lMSgTnWW'>

- $\vec{x}$ is a list of the pixel intensity values

## 2.1.3.2 Data in TensorFlow

- For historical reasons, there are some inconsistencies between how data is represented in `numpy` and `TensorFlow`
- TensorFlow was designed to handle very large datasets and by representing the data as matrices instead of 1D arrays, which enables TensorFlow to be a bit more computationally efficient internally

### How `TensorFlow` represents data

<img src='https://drive.google.com/uc?export=view&id=1lyizo54f-gcGrvZOrCkysPyUyT-HQOZb'>

In [11]:
# feature vector
# 1 X 2 matrix
x = np.array([[200.0, 17.0]])
x, x.shape

(array([[200.,  17.]]), (1, 2))

In [12]:
# alternate feature vector
# 1 X 2 matrix
x = np.array([200.0, 17.0]).reshape(1, -1)
x, x.shape

(array([[200.,  17.]]), (1, 2))

In [13]:
# not a 2D array
# not a matrix
# this is a 1D array with
# a 1D "vector" with no rows or columns
x = np.array([200.0, 17.0])
x, x.shape

(array([200.,  17.]), (2,))

- Why the double square brackets in the feature vector?
    - Because we need a **matrix** which is a 2D array

### Some of the code for carrying out forward propagation

#### First layer

<img src='https://drive.google.com/uc?export=view&id=1ScnwOI2iNkC2tPXNjj-RiJzxAHqe6FPM'>

- What is `a1`?
 - it is a $1 \times 3$ matrix:
 - `tf.Tensor([[0.2 0.7 0.3]], shape=(1, 3), dtype=float32)`
 - a **Tensor** is a data type created to store and carry out computations on matrices efficiently
 - in this course it is ok to think of a tensor as a matrix
 - technically, a tensor is a little bit more general than a matrix
- a tensor can be coverted to a `numpy` array
 - `a1.numpy()`

#### Second layer

<img src='https://drive.google.com/uc?export=view&id=1NGpxy9kmOGGLN7FkiLMl1wkKkIDaeleZ'>

- `a2` is a number, but it is represented by a $1 \times 1$ matrix


## 2.1.3.3 Building a neural network

### Forward Propagation: One layer at time

<img src='https://drive.google.com/uc?export=view&id=1BUtqc_y5uY99etlz5ZwH8KEioxecQwp4'>

### Forward Progagation: Using `Sequential`

<img src='https://drive.google.com/uc?export=view&id=1ngKVbPXzILpqC7Ileohtu5GmVz2_V1RW'>

Alternately:

<img src='https://drive.google.com/uc?export=view&id=1qgnKKrOWxVlEfGmcRFHS9g0Bke2C01s5'>

- to find `a2`: `model.predict(x_new)`
- `model.predict` carries out forward propagation


### Training: more on this next week

<img src='https://drive.google.com/uc?export=view&id=1jswiQTa1W42oancLunvcfsFJRkJ_Cjyr'>




In [14]:
x = np.array([[200.0, 17.0],
              [120.0, 5.0],
              [425.0, 20.0],
              [212.0, 180.]])
y = np.array([1, 0, 0, 1])

In [15]:
model = Sequential([
    Dense(units=3, activation='sigmoid'),
    Dense(units=1, activation='sigmoid')
])

model

In [16]:
model.layers[1]

In [17]:
model.get_layer(index=1)

In [18]:
# model.predict carries out forward propagation
model.predict(x)

1/1 [==============================] - 0s 203ms/step


array([[0.62837833],
       [0.62837833],
       [0.62837833],
       [0.5706036 ]], dtype=float32)

### Digit classification example

<img src='https://drive.google.com/uc?export=view&id=11O7Y2f7JesY-bSGrp5hNahGBEdFLmDmH'>

## 2.1.3.4 Lab - Coffee Roasting in TensorFlow

https://colab.research.google.com/drive/1soMCVgYzFMbOBbfWvTPBqfyK3C2N6svP